name: CI Build Deploy

on:
  push:
    branches:
      - gacha

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Android with Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2022.3.5f1
          targetPlatform: Android
          buildName: FreedomRoad-gacha.apk
          buildPath: build/android
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: Gacha-APK
          path: build/android/FreedomRoad-gacha.apk
